name: tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7.x'
          - '3.0.x'
          - '3.1.x'
        active_support:
          - '6.0.0'
          - '6.1.0'
          - '7.0.0'
        assets_gem:
          - 'sprockets-rails'
          - 'propshaft'
        exclude:
          - active_support: '6.0.0'
            assets_gem: 'propshaft'
          - active_support: '6.1.0'
            assets_gem: 'propshaft'

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle
        env:
          ACTION_MAILER_VERSION: ${{ matrix.active_support }}
          ASSETS_GEM: ${{ matrix.assets_gem }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Test
        env:
          ACTION_MAILER_VERSION: ${{ matrix.active_support }}
          ASSETS_GEM: ${{ matrix.assets_gem }}
        run: bundle exec rspec
